spring:
  application:
    name: docsCenterGradleGenerated
  servlet:
    multipart:
      max-file-size: 2500MB
      max-request-size: 2500MB
  datasource:
    url: jdbc:sqlite:/data/storage.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
